version: 3
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run: 
          name: "Build development images"
          command: docker-compose build
      - run:
          name: "Test front"
          command: docker-compose run --rm -e CI=true client npm run -s test
          when: on_success
      - run:
          name: "Test cypress"
          command: docker-compose run --rm -e CI=true client npm run cy:run
    
  # test:
  #   steps:
  #     - checkout
  #     - run: yarn
  #     - run: yarn test
  # cypress:
  #   docker:
  #     - image: node
  #   steps:
  #     - checkout
  #     - run: docker-compose -f dev-docker-compose.yml up --build
  #     - run: yarn cy:run
  
workflows:
  version: 3
  build_and_test:
    jobs:
      - build
      # - test
      # - cypress:
      #     requires:
      #       - build