version: 2
jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - run: cd client && yarn
      - run: cd client && yarn build
  # test:
  #   steps:
  #     - checkout
  #     - run: yarn
  #     - run: yarn test
  cypress:
    docker:
      - image: node
    steps:
      - checkout
      - run: docker-compose -f dev-docker-compose.yml up --build
      - run: yarn cy:run
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # - test
      - cypress:
          requires:
            - build