version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run: 
          name: "Build development images"
          command: docker-compose -f dev-docker-compose.yml build
      - run:
          name: "Test front"
          command: dev-docker-compose run --rm -e CI=true client yarn run -s test
      - run:
          name: "Test cypress"
          command: dev-docker-compose run --rm -e CI=true client yarn run cy:run
  # test:
  #   steps:
  #     - checkout
  #     - run: yarn
  #     - run: yarn test
  # cypress:
  #   docker:
  #     - image: node
  #   steps:
  #     - checkout
  #     - run: docker-compose -f dev-docker-compose.yml up --build
  #     - run: yarn cy:run
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # - test
      # - cypress:
      #     requires:
      #       - build