version: '3.7'

services:

  server:
    container_name: docker-mern-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:8080'
    environment:
      - NODE_ENV=development